// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeakResponse = { success: boolean, 
/**
 * Set when the requested voice or language was unavailable and the default was used.
 * Speech still happens.
 */
warning?: string | null, 
/**
 * Matches the `id` on this utterance's lifecycle events.
 */
utteranceId?: string | null, };
