// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueMode } from "./QueueMode";

export type SpeakOptions = { 
/**
 * Text to speak, at most [`crate::validation::MAX_TEXT_LENGTH`] UTF-8 bytes.
 */
text: string, 
/**
 * Locale code such as `en-US`, `pt-BR` or `ja-JP`.
 */
language?: string | null, 
/**
 * Voice ID from `getVoices`. Takes priority over `language`.
 */
voiceId?: string | null, 
/**
 * Speech rate, 0.1 to 4.0, where 1.0 is the platform's normal.
 */
rate?: number | null, 
/**
 * Pitch, 0.5 to 2.0, where 1.0 is the platform's normal.
 */
pitch?: number | null, 
/**
 * Volume, 0.0 to 1.0.
 */
volume?: number | null, queueMode?: QueueMode | null, };
